# Generated by Django 4.2.6 on 2023-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serializer_App', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[(1, '★'), (2, '★★'), (3, '★★★')], max_length=3),
        ),
    ]
